site_name: My Dotfiles
site_description: Personal configurations, scripts, technical notes, etc.
repo_url: https://github.com/habedi/dotfiles
repo_name: habedi/dotfiles
site_url: https://habedi.github.io/dotfiles/

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/habedi/dotfiles

plugins:
  - search

nav:
  - Home: index.md
  - Zig: zig.md
  - Rust: rust.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
